version: '3'

services:
  clickhouse-server:
    container_name: clickhouse-server
    image: psyoblade/data-engineer-clickhouse-server:22.2.2.1
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  clickhouse-client:
    container_name: clickhouse-client
    image: psyoblade/data-engineer-clickhouse-client:22.2.2.1
    restart: always
    tty: yes
    depends_on:
      - clickhouse-server
    links:
      - clickhouse-server
    volumes:
      - ./data:/tmp/data
    command: ['--host', 'clickhouse-server']

networks:
  default:
    name: default_network
