management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    username: default
    password:
    url: jdbc:clickhouse://127.0.0.1:8123/default
    connectionTimeout: 67000
    hikari:
      connectionTimeout: 67000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    database-platform: me.suhyuk.jdbc.config.ClickhouseDialect