management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8088
spring:
  datasource:
    driverClassName: com.clickhouse.jdbc.ClickHouseDriver
    username: default
    password:
    jdbcUrl: jdbc:clickhouse://127.0.0.1:8123/default
    connectionTimeout: 67000
    hikari:
      connectionTimeout: 67000
      idleTimeout: 600000
      maxLifetime: 1800000
  h2:
    driverClassName: org.h2.Driver
    username: sa
    password:
    jdbcUrl: jdbc:h2:tcp://localhost/~/test
    h2:
      console:
        enabled: true
  mysql:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
    jdbcUrl: jdbc:mysql://localhost:3306/SELECT-SERVER?serverTimezone=UTC&characterEncoding=UTF-8
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      hbm2ddl:
        auto: create